lxqt_packages:
  - lxqt-panel
  - lxqt-session
  - lxqt-config
  - lxqt-runner
  - lxqt-policykit
  - lxqt-notificationd
  - lxqt-qtplugin
  - pcmanfm-qt
  - openbox
  - qterminal
  - xorg
  - xinit

lxqt_config:
  - lxqt.conf
  - panel.conf

# 'files' ar copied to their destination
files:
  - Name: TextViewer.desktop
    Dest: /usr/share/applications/TextViewer.desktop
  - Name: mimeapps.list
    Dest: /home/{{ username }}/.config/mimeapps.list
