lxqt_packages:
  - lxqt-panel
  - lxqt-session
  - lxqt-config
  - lxqt-runner
  - lxqt-policykit
  - lxqt-notificationd
  - lxqt-qtplugin
  - pcmanfm-qt
  - openbox
  - upower
  - polkitd
  - qterminal
  - xorg
  - xinit
  - papirus-icon-theme

# 'files' are copied to their destination
files:
  - Name: lxqt.conf
    Dest: /home/{{ username }}/.config/lxqt/lxqt.conf
  - Name: panel.conf
    Dest: /home/{{ username }}/.config/lxqt/panel.conf
  - Name: TextViewer.desktop
    Dest: /usr/share/applications/TextViewer.desktop
  - Name: mimeapps.list
    Dest: /home/{{ username }}/.config/mimeapps.list
