packages:
# General purpose
  - firefox-esr
  - git
  - python3 # Should already exist to use ansible
# PHP
  - php
  - php-curl
  - php-cli
  - php-bcmath
  - php-json
  - php-mbstring
  - php-xml
  - php-tokenizer
  - php-zip
# Sqlite
  - sqlite3
  - php-sqlite3

# VS Code Server
code_server_version: 4.108.2
code_server_port: 8080
code_server_password: "{{ password }}"
