---

- name: Remove unnecessary packages
  ansible.builtin.apt:
    name: "{{ unnecessary_packages }}"
    state: absent
    purge: true
  become: true

- name: Autoremove unused packages
  ansible.builtin.apt:
    autoremove: true
  become: true

- name: Clean APT cache
  ansible.builtin.apt:
    autoclean: true
  become: true

- name: Remove downloaded packages
  ansible.builtin.apt:
    clean: true
  become: true
