---

- name: Remove unnecessary packages
  ansible.builtin.apt:
    name: "{{ unnecessary_packages }}""
    state: absent
  become: true

- name: Clean APT cache
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    clean: true
  become: true
