---

- name: Create cron job for generating id at boot
  cron:
    name: "Generate VM ID"
    job: "/usr/local/bin/dvmconf create id $(cat /proc/sys/kernel/random/uuid)"
    user: root
    special_time: reboot

- name: Create cron job for telemetry script
  cron:
    name: "Run combine"
    job: "/usr/local/bin/combine"
    user: root
    minute: "*/10"
