---

- name: Create cron job for generating id at boot
  cron:
    name: "Generate VM ID"
    job: "/usr/local/sbin/generate-id"
    user: root
    special_time: reboot

- name: Create cron job for telemetry script
  cron:
    name: "Run combine"
    job: "/usr/local/bin/combine"
    user: root
    minute: "*/10"
