---

- name: Create dvm directory
  file:
    path: "/etc/dvm"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Create combine config
  ansible.builtin.template:
    src: "combine.conf.j2"
    dest: "/etc/dvm/combine.conf"
    mode: "0766"
  become: true

- name: Create Desktop directory
  file:
    path: "/home/{{ username }}/Desktop"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  become: true

- name: Create a text file from a template on the desktop
  ansible.builtin.template:
    src: "README.txt.j2"
    dest: "/home/{{ username }}/Desktop/README.txt"
    mode: "0644"
  become: false

- name: Create projects directory
  file:
    path: "/home/{{ username }}/Projects"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  become: true

- name: Create scripts from templates into /usr/local/bin
  ansible.builtin.template:
    src: "{{ item.Name }}{{ item.Extension }}.j2"
    dest: "/usr/local/bin/{{ item.Name }}"
    mode: "0755"
  loop: "{{ scripts }}"

- name: Create scripts from templates into /usr/local/sbin
  ansible.builtin.template:
    src: "{{ item.Name }}{{ item.Extension }}.j2"
    dest: "/usr/local/sbin/{{ item.Name }}"
    mode: "0755"
  loop: "{{ su_scripts }}"
