unnecessary_packages:
  - laptop-detect
  - tasksel
# Graphics
  - mesa-vulkan-drivers
  - xserver-xorg-video-amdgpu
  - xserver-xorg-video-fbdev
  - xserver-xorg-video-intel
  - xserver-xorg-video-nouveau
  - xserver-xorg-video-qxl
  - xserver-xorg-video-radeon
# Locales & language
  - ispell
# Networking
  - nftables
# Storage & filesystem
  - eject
