unnecessary_packages:
  - avahi-daemon
#  - gnome-accessibility-themes
#  - ipp-usb
  - laptop-detect
  - libgphoto2-l10n
  - libldap-common
#  - libwebrtc-audio-processing1
  - mesa-vulkan-drivers
#  - sane-airscan
  - tasksel
  - upower
  - xcvt
# - xiccd
  - xscreensaver
  - xserver-xorg-legacy
# Audio & multimedia
  - alsa-topology-conf
  - alsa-ucm-conf
  - pipewire
  - pulseaudio
  - pulseaudio-utils
  - wireplumber
# Storage
  - dosfstools
  - ntfs-3g

